package org.openjproxy.grpc.server.statement;

import com.openjproxy.grpc.StatementRequest;
import org.apache.commons.lang3.StringUtils;
import org.openjproxy.constants.CommonConstants;
import org.openjproxy.grpc.ProtoConverter;
import org.openjproxy.grpc.dto.Parameter;
import org.openjproxy.grpc.server.ConnectionSessionDTO;
import org.openjproxy.grpc.server.SessionManager;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Map;

import static org.openjproxy.grpc.server.Constants.EMPTY_MAP;

/**
 * Factory class for creating different types of SQL statements.
 * Extracted from StatementServiceImpl to improve modularity.
 */
public class StatementFactory {

    /**
     * Creates a Statement based on the request properties.
     *
     * @param sessionManager The session manager
     * @param connection    The database connection
     * @param request       The statement request
     * @return Created Statement
     * @throws SQLException if statement creation fails
     */
    public static Statement createStatement(SessionManager sessionManager, Connection connection, 
                                          StatementRequest request) throws SQLException {
        try {
            if (StringUtils.isNotEmpty(request.getStatementUUID())) {
                return sessionManager.getStatement(request.getSession(), request.getStatementUUID());
            }
            if (request.getPropertiesList().isEmpty()) {
                return connection.createStatement();
            }
            Map<String, Object> properties = ProtoConverter.propertiesFromProto(request.getPropertiesList());

            if (properties.isEmpty()) {
                return connection.createStatement();
            }

            Integer resultSetType = (Integer) properties.get(CommonConstants.STATEMENT_RESULT_SET_TYPE_KEY);
            Integer resultSetConcurrency = (Integer) properties.get(CommonConstants.STATEMENT_RESULT_SET_CONCURRENCY_KEY);
            Integer resultSetHoldability = (Integer) properties.get(CommonConstants.STATEMENT_RESULT_SET_HOLDABILITY_KEY);

            if (resultSetType != null && resultSetConcurrency != null && resultSetHoldability != null) {
                return connection.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
            }
            if (resultSetType != null && resultSetConcurrency != null) {
                return connection.createStatement(resultSetType, resultSetConcurrency);
            }
            // For any other property combinations (e.g. PREPARED_STATEMENT_SQL_KEY,
            // STATEMENT_AUTO_GENERATED_KEYS_KEY used on the Statement path), create a plain statement.
            return connection.createStatement();
        } catch (RuntimeException re) {
            throw new SQLException("Unable to create statement: " + re.getMessage(), re);
        }
    }

    /**
     * Creates a PreparedStatement with the given SQL and parameters.
     *
     * @param sessionManager The session manager
     * @param dto           The connection session DTO
     * @param sql           The SQL statement
     * @param params        The parameters
     * @param request       The statement request
     * @return Created PreparedStatement
     * @throws SQLException if prepared statement creation fails
     */
    public static PreparedStatement createPreparedStatement(SessionManager sessionManager, 
                                                          ConnectionSessionDTO dto, String sql, 
                                                          List<Parameter> params, StatementRequest request)
            throws SQLException {

        PreparedStatement ps = null;
        Map<String, Object> properties = EMPTY_MAP;
        if (!request.getPropertiesList().isEmpty()) {
            properties = ProtoConverter.propertiesFromProto(request.getPropertiesList());
        }

        // Look up each creation-relevant property independently.
        // PREPARED_STATEMENT_SQL_KEY is informational and intentionally ignored here.
        // STATEMENT_COLUMN_INDEXES_KEY is stored as List<Integer> on the client side and
        // arrives as List<Double> after ProtoSerialization (all Numbers serialise as double).
        // STATEMENT_COLUMN_NAMES_KEY is stored as List<String> and arrives as List<String>.
        List<?> columnIndexList = (List<?>) properties.get(CommonConstants.STATEMENT_COLUMN_INDEXES_KEY);
        List<?> columnNameList = (List<?>) properties.get(CommonConstants.STATEMENT_COLUMN_NAMES_KEY);
        Boolean isAddBatch = (Boolean) properties.get(CommonConstants.PREPARED_STATEMENT_ADD_BATCH_FLAG);
        Integer autoGeneratedKeys = (Integer) properties.get(CommonConstants.STATEMENT_AUTO_GENERATED_KEYS_KEY);
        Integer resultSetType = (Integer) properties.get(CommonConstants.STATEMENT_RESULT_SET_TYPE_KEY);
        Integer resultSetConcurrency = (Integer) properties.get(CommonConstants.STATEMENT_RESULT_SET_CONCURRENCY_KEY);
        Integer resultSetHoldability = (Integer) properties.get(CommonConstants.STATEMENT_RESULT_SET_HOLDABILITY_KEY);

        if (columnIndexList != null) {
            int[] columnIndexes = new int[columnIndexList.size()];
            for (int i = 0; i < columnIndexList.size(); i++) {
                columnIndexes[i] = ((Number) columnIndexList.get(i)).intValue();
            }
            ps = dto.getConnection().prepareStatement(sql, columnIndexes);
        } else if (columnNameList != null) {
            String[] columnNames = columnNameList.toArray(new String[0]);
            ps = dto.getConnection().prepareStatement(sql, columnNames);
        } else if (autoGeneratedKeys != null) {
            ps = dto.getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
        } else if (resultSetType != null && resultSetConcurrency != null && resultSetHoldability != null) {
            ps = dto.getConnection().prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
        } else if (resultSetType != null && resultSetConcurrency != null) {
            ps = dto.getConnection().prepareStatement(sql, resultSetType, resultSetConcurrency);
        } else {
            // Covers: empty properties, PREPARED_STATEMENT_SQL_KEY only, isAddBatch flag, or any unknown combination
            ps = dto.getConnection().prepareStatement(sql);
        }

        ParameterHandler.addParametersPreparedStatement(sessionManager, dto.getSession(), ps, params);
        return ps;
    }
}