package org.openjproxy.grpc.server.action.transaction;

import com.openjproxy.grpc.*;
import io.grpc.stub.StreamObserver;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.collections4.CollectionUtils;
import org.apache.commons.lang3.StringUtils;
import org.openjproxy.constants.CommonConstants;
import org.openjproxy.grpc.ProtoConverter;
import org.openjproxy.grpc.dto.Parameter;
import org.openjproxy.grpc.server.*;
import org.openjproxy.grpc.server.action.Action;
import org.openjproxy.grpc.server.action.ActionContext;
import org.openjproxy.grpc.server.action.util.ProcessClusterHealthAction;
import org.openjproxy.grpc.server.sql.SqlSessionAffinityDetector;
import org.openjproxy.grpc.server.statement.ParameterHandler;
import org.openjproxy.grpc.server.statement.StatementFactory;
import org.openjproxy.grpc.server.utils.StatementRequestValidator;

import java.sql.PreparedStatement;
import java.sql.SQLDataException;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import static org.openjproxy.grpc.server.GrpcExceptionHandler.sendSQLExceptionMetadata;
import static org.openjproxy.grpc.server.action.streaming.SessionConnectionHelper.sessionConnection;

@SuppressWarnings("java:S6548")
@Slf4j
public class ExecuteUpdateAction implements Action<StatementRequest, OpResult> {

    private static final String UPDATE = "update";

    private static final ExecuteUpdateAction INSTANCE = new ExecuteUpdateAction();

    private ExecuteUpdateAction() {
        // Private empty constructor
    }

    /**
     * Returns the singleton instance of this action.
     *
     * @return the singleton instance
     */
    public static ExecuteUpdateAction getInstance() {
        return INSTANCE;
    }

    @SneakyThrows
    @Override
    public void execute(ActionContext context, StatementRequest request, StreamObserver<OpResult> responseObserver) {
        log.info("Executing update {}", request.getSql());

        executeWithResilience(context, request, responseObserver,
                () -> {
                    OpResult result = executeUpdateInternal(context, request);
                    responseObserver.onNext(result);
                    responseObserver.onCompleted();
                });
    }

    /**
     * Internal method for executing updates without segregation logic.
     */
    @SuppressWarnings("unchecked")
    private OpResult executeUpdateInternal(ActionContext actionContext, StatementRequest request) throws SQLException {
        int updated = 0;
        SessionInfo returnSessionInfo;
        ConnectionSessionDTO dto = ConnectionSessionDTO.builder().build();

        Statement stmt = null;
        String psUUID = "";
        OpResult.Builder opResultBuilder = OpResult.newBuilder();

        var sessionManager = actionContext.getSessionManager();

        try {
            // Check if SQL requires session affinity (temporary tables, session variables,
            // etc.)
            boolean requiresSessionAffinity = SqlSessionAffinityDetector.requiresSessionAffinity(request.getSql());

            dto = sessionConnection(actionContext, request.getSession(),
                    StatementRequestValidator.isAddBatchOperation(request)
                            || StatementRequestValidator.hasAutoGeneratedKeysFlag(request)
                            || requiresSessionAffinity);
            returnSessionInfo = dto.getSession();

            List<Parameter> params = ProtoConverter.fromProtoList(request.getParametersList());
            PreparedStatement ps = dto.getSession() != null && StringUtils.isNotBlank(dto.getSession().getSessionUUID())
                    && StringUtils.isNoneBlank(request.getStatementUUID())
                            ? sessionManager.getPreparedStatement(dto.getSession(), request.getStatementUUID())
                            : null;
            if (CollectionUtils.isNotEmpty(params) || ps != null) {
                if (StringUtils.isNotEmpty(request.getStatementUUID()) && ps != null) {
                    Collection<Object> lobs = sessionManager.getLobs(dto.getSession());
                    for (Object o : lobs) {
                        LobDataBlocksInputStream lobIS = (LobDataBlocksInputStream) o;
                        Map<String, Object> metadata = (Map<String, Object>) sessionManager.getAttr(dto.getSession(),
                                lobIS.getUuid());
                        Integer parameterIndex = (Integer) metadata
                                .get(CommonConstants.PREPARED_STATEMENT_BINARY_STREAM_INDEX + "");
                        ps.setBinaryStream(parameterIndex, lobIS);
                    }
                    if (DbName.POSTGRES.equals(dto.getDbName())) {// Postgres requires check if the lob streams are
                        // fully consumed.
                        sessionManager.waitLobStreamsConsumption(dto.getSession());
                    }
                    ParameterHandler.addParametersPreparedStatement(sessionManager, dto.getSession(), ps, params);
                } else {
                    ps = StatementFactory.createPreparedStatement(sessionManager, dto, request.getSql(), params,
                            request);
                    if (StatementRequestValidator.hasAutoGeneratedKeysFlag(request)) {
                        String psNewUUID = sessionManager.registerPreparedStatement(dto.getSession(), ps);
                        opResultBuilder.setUuid(psNewUUID);
                    }
                }
                if (StatementRequestValidator.isAddBatchOperation(request)) {
                    ps.addBatch();
                    if (request.getStatementUUID().isBlank()) {
                        psUUID = sessionManager.registerPreparedStatement(dto.getSession(), ps);
                    } else {
                        psUUID = request.getStatementUUID();
                    }
                } else {
                    updated = ps.executeUpdate();
                }
                stmt = ps;
            } else {
                stmt = StatementFactory.createStatement(sessionManager, dto.getConnection(), request);
                updated = stmt.executeUpdate(request.getSql());
            }

            if (StatementRequestValidator.isAddBatchOperation(request)) {
                return opResultBuilder
                        .setType(ResultType.UUID_STRING)
                        .setSession(returnSessionInfo)
                        .setUuidValue(psUUID).build();
            } else {
                return opResultBuilder
                        .setType(ResultType.INTEGER)
                        .setSession(returnSessionInfo)
                        .setIntValue(updated).build();
            }
        } finally {
            // If there is no session, close statement and connection
            if ((dto.getSession() == null || StringUtils.isEmpty(dto.getSession().getSessionUUID())) && stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException e) {
                    log.error("Failure closing statement: {}", e.getMessage(), e);
                }
                try {
                    stmt.getConnection().close();
                } catch (SQLException e) {
                    log.error("Failure closing connection: {}", e.getMessage(), e);
                }
            }

        }
    }

    /**
     * Helper method to centralize session validation, activity updates, cluster
     * health processing,
     * circuit breaker checks, and slow query segregation for statement execution.
     * This resolves SonarQube duplication issues.
     */
    private void executeWithResilience(ActionContext context, StatementRequest request,
            StreamObserver<OpResult> responseObserver,
            StatementExecution executionLogic) {

        // Ensure session isn't null
        if (StringUtils.isBlank(request.getSession().getConnHash())) {
            sendSQLExceptionMetadata(new SQLException("Invalid request: Session or ConnHash is missing"),
                    responseObserver);
            log.error("Invalid {} request: Session or ConnHash is missing", UPDATE);
            return;
        }

        // Update session activity
        updateSessionActivity(context, request.getSession());

        String stmtHash = SqlStatementXXHash.hashSqlQuery(request.getSql());
        // Process cluster health from the request
        ProcessClusterHealthAction.getInstance().execute(context, request.getSession());

        String connHash = request.getSession().getConnHash();
        CircuitBreaker circuitBreaker = context.getCircuitBreakerRegistry().get(connHash);

        // Get the appropriate slow query segregation manager for this datasource
        SlowQuerySegregationManager manager = getSlowQuerySegregationManagerForConnection(context, connHash);
        long sqlStartMs = System.currentTimeMillis();
        try {
            circuitBreaker.preCheck(stmtHash);

            // Execute with slow query segregation, passing actual SQL for metric labelling
            manager.executeWithSegregation(stmtHash, request.getSql(), () -> {
                executionLogic.execute();
                return null;
            });

            circuitBreaker.onSuccess(stmtHash);

        } catch (SQLDataException e) {
            circuitBreaker.onFailure(stmtHash, e);
            log.error("SQL data failure during {} execution: {}",
                    UPDATE, e.getMessage(), e);

            sendSQLExceptionMetadata(e, responseObserver, SqlErrorType.SQL_DATA_EXCEPTION);

        } catch (SQLException e) {
            circuitBreaker.onFailure(stmtHash, e);
            log.error("SQL failure during {} execution: {}",
                    UPDATE, e.getMessage(), e);
            sendSQLExceptionMetadata(e, responseObserver);
        } catch (Exception e) {
            log.error("Unexpected failure during {} execution: {}",
                    UPDATE, e.getMessage(), e);
            if (e.getCause() instanceof SQLException sqlException) {
                circuitBreaker.onFailure(stmtHash, sqlException);
                sendSQLExceptionMetadata(sqlException, responseObserver);
            } else {
                SQLException sqlException = new SQLException("Unexpected error: " + e.getMessage(), e);
                circuitBreaker.onFailure(stmtHash, sqlException);
                sendSQLExceptionMetadata(sqlException, responseObserver);
            }
        } finally {
            // Record SQL execution time for all connections (XA and non-XA) regardless of
            // manager state. This is the single authoritative place for SQL metrics.
            String sql = request.getSql();
            if (!sql.isEmpty()) {
                long executionTimeMs = System.currentTimeMillis() - sqlStartMs;
                context.getSqlStatementMetrics().recordSqlExecution(
                        sql, executionTimeMs, manager.isSlowOperation(stmtHash));
            }
        }
    }

    /**
     * Updates the last activity time for the session to prevent premature cleanup.
     * This should be called at the beginning of any method that operates on a
     * session.
     *
     * @param sessionInfo the session information
     */
    private void updateSessionActivity(ActionContext context, SessionInfo sessionInfo) {
        if (sessionInfo != null && !sessionInfo.getSessionUUID().isEmpty()) {
            context.getSessionManager().updateSessionActivity(sessionInfo);
        }
    }

    /**
     * Gets the slow query segregation manager for a specific connection hash.
     * If no manager exists, creates a disabled one as a fallback.
     */
    private SlowQuerySegregationManager getSlowQuerySegregationManagerForConnection(ActionContext context,
            String connHash) {
        var slowQuerySegregationManagers = context.getSlowQuerySegregationManagers();

        SlowQuerySegregationManager manager = slowQuerySegregationManagers.get(connHash);
        if (manager == null) {
            log.warn("No SlowQuerySegregationManager found for connection hash {}, creating disabled fallback",
                    connHash);
            manager = new SlowQuerySegregationManager(1, 0, 0, 0, 0, 0, false);
            slowQuerySegregationManagers.put(connHash, manager);
        }
        return manager;
    }

    @FunctionalInterface
    private interface StatementExecution {
        void execute() throws Exception;
    }
}
